name: attention-tf2-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - notebook
  - jupyter_contrib_nbextensions
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - opencv
  - pydot
  - scikit-learn
  - pytest
  - lime
  - scikit-image
  - google-cloud-storage
  - tensorflow=2.3.*
  - tensorflow-datasets
  - pip
  - pip:
    - tensorflow-addons
    - keras-flops
