name: attention-tf2-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - notebook
  - jupyter_contrib_nbextensions
  - ipywidgets
  - numpy=1.18.5
  - pandas
  - matplotlib
  - opencv
  - pydot
  - scikit-learn
  - pytest
  - lime
  - scikit-image
  - google-cloud-storage
  - pip
  - pip:
    - tensorflow==2.3.0
    - tensorflow-datasets
    - tensorflow-addons
    - keras-flops
    - tensorboard-plugin-profile
