name: attention-tf2-cpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - notebook
  - jupyter_contrib_nbextensions
  - ipywidgets
  - numpy=1.19.*
  - pandas
  - matplotlib
  - opencv
  - pydot
  - scikit-learn
  - pytest
  - tensorflow=2.3.*
  - tensorflow-datasets
