name: attention-tf2-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8.*
  - notebook
  - jupyter_contrib_nbextensions
  - numpy
  - pandas
  - matplotlib
  - opencv
  - pydot
  - cudatoolkit=10.1
  - pip
  - pip:
    - tensorflow-gpu==2.3.0
