name: attention-tf2-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - notebook
  - jupyter_contrib_nbextensions
  - numpy
  - pandas
  - matplotlib
  - opencv
  - pydot
  - scikit-learn
  - cudatoolkit=10.1 # requires cuDNN 7.6
  - pip
  - pip:
    - tensorflow-gpu==2.3.0