name: attention-tf2-gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - notebook
  - jupyter_contrib_nbextensions
  - numpy==1.18.5
  - pandas
  - matplotlib
  - opencv
  - pydot
  - scikit-learn
  - cudatoolkit=11.2 # requires cuDNN 8.1
  - pip
  - pip:
    - tensorflow-gpu==2.5.0